export const data = [
  {
    id: 1,
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1352080/ss_b767442baf8dd83b3a8d07714f735ace97e05e53.1920x1080.jpg?t=1615884157",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "mobile",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 2,
    img: "https://i.redd.it/f0h5j6aaefm81.jpg",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "mobile",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 3,
    img: "https://i.ytimg.com/vi/kHiYkYY05xc/maxresdefault.jpg",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "pc",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 4,
    img: "https://www.droidgamers.com/wp-content/uploads/2021/08/smash-legends-robin-half-year-celebration-artwork.jpg",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "controller",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 5,
    img: "https://www.gamemonday.com/wp-content/uploads/2021/09/Smash-Legends-2992021.jpg",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "pc",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 6,
    img: "https://tse3.mm.bing.net/th?id=OIP.YcLXyB-HwKVSJel7-c4RGQHaDt&pid=Api&P=0&h=180",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "controller",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 7,
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1352080/ss_b767442baf8dd83b3a8d07714f735ace97e05e53.1920x1080.jpg?t=1615884157",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "mobile",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 8,
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1352080/ss_b767442baf8dd83b3a8d07714f735ace97e05e53.1920x1080.jpg?t=1615884157",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "pc",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
  {
    id: 9,
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1352080/ss_b767442baf8dd83b3a8d07714f735ace97e05e53.1920x1080.jpg?t=1615884157",
    orgName: "Hellyeah",
    gameName: "Smash-legend",
    date: "27 june-30 june,2024",
    numOfParticipant: 127,
    category: "controller",
    prizePool: {
      first: "$5000",
      second: "$3000",
      third: "$1000",
    },
    schedule: {
      registrationDeadline: "25 June, 2024",
      startDate: "27 June, 2024",
      endDate: "30 June, 2024",
      finals: "30 June, 2024 - 5:00 PM",
    },
    rules: [
      "Players must use the official tournament app for participation.",
      "Matches must be played within the allocated time slots.",
      "Cheating, exploiting, or unsportsmanlike behavior is strictly prohibited.",
      "Participants must register with their real identity.",
    ],
    description:
      "Welcome to the Smash Legend Championship! Compete against the best players in the world for a chance to claim glory and a share of the $9000 prize pool. This is a mobile-only tournament, featuring fast-paced action and epic battles. Don't miss out!",
    platform: "Online - Discord & Smash Legend App",
    sponsors: ["GameCorp", "TechMaster", "PlayArena"],
    streamingInfo: "All matches will be live-streamed on Twitch and YouTube.",
  },
];
